{% set name = "nonbonded" %}
{% set version = "0.0.1a4" %}
{% set sha256 = "8035a8bda53c653ac7941c74b58d6040b3897a8ef1edf1d30a12b0356189b26c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/simonboothroyd/{{ name }}/archive/{{ version | replace("a", "-alpha.") }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - nonbonded = nonbonded.cli:cli

requirements:
  host:
    - python
    - pip
  run:

    - python

      # Core dependencies
    - click
    - click-option-group
    - numpy
    - pydantic
    - requests
    - pandas
    - jinja2
    - email_validator

      # Benchmark / optimization target dependencies
    - forcebalance >=1.7.5
    - openforcefield >=0.8.0
    - openff-evaluator >=0.2.0
    - openff-recharge >=0.0.1a6

      # SMILES to SVG
    - rdkit

      # Plotting
    - seaborn >=0.11

      # Statistics
    - scipy

      # REST dependencies
    - sqlalchemy
    - sqlalchemy-utils

test:
  imports:
    - nonbonded

about:
  home: https://github.com/simonboothroyd/nonbonded
  license: MIT
  license_file: LICENSE
  description: Automated optimization and assesment of nonbonded force field parameters.

extra:
  recipe-maintainers:
    - simonboothroyd