{% set name = "nonbonded" %}
{% set version = "0.0.1b2" %}
{% set sha256 = "251d88caf47e3a56dc22ad81380a0e7d667413db9f7d93f2278208c8d1b45c3e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/simonboothroyd/{{ name }}/archive/{{ version | replace("b", "-beta.") }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - nonbonded = nonbonded.cli:cli

requirements:
  host:
    - python
    - pip
  run:

    - python

      # Core dependencies
    - click
    - click-option-group
    - numpy
    - pydantic
    - requests
    - pandas
    - jinja2
    - email_validator

      # Benchmark / optimization target dependencies
    - forcebalance >=1.7.5
    - openff-toolkit-base
    - openff-evaluator >=0.3.3
    - openff-recharge >=0.0.1

      # SMILES to SVG
    - rdkit

      # Plotting
    - seaborn >=0.11

      # Statistics
    - scipy

      # REST dependencies
    - sqlalchemy <1.4.0
    - sqlalchemy-utils

test:
  imports:
    - nonbonded

about:
  home: https://github.com/simonboothroyd/nonbonded
  license: MIT
  license_file: LICENSE
  description: Automated optimization and assesment of nonbonded force field parameters.

extra:
  recipe-maintainers:
    - simonboothroyd